#  Countries - Year benefit

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

In [3]:
data_in= pd.read_csv('retail_sales_clean.csv')
data_in.head()

,Year,Product line,Product type,Product,Order method type,Retailer country,Revenue,Planned revenue,Product cost,Quantity,Unit cost,Unit price,Gross profit,Unit sale price
0,2004,Camping Equipment,Cooking Gear,TrailChef Water Bag,Telephone,United States,315044.33,437477.15,158371.76,66385.0,2.552857,6.59,156672.57,5.195714
1,2004,Camping Equipment,Cooking Gear,TrailChef Water Bag,Telephone,Canada,13444.68,14313.48,6298.80,2172.0,2.900000,6.59,7145.88,6.190000
2,2004,Camping Equipment,Cooking Gear,TrailChef Water Bag,Telephone,Japan,181120.24,235236.64,89413.06,35696.0,2.657000,6.59,91707.18,5.488000
3,2004,Camping Equipment,Cooking Gear,TrailChef Water Bag,Telephone,China,69608.15,100200.95,35326.25,15205.0,2.495000,6.59,34281.90,5.040000
4,2004,Camping Equipment,Cooking Gear,TrailChef Water Bag,Telephone,Singapore,30940.35,51619.47,16370.97,7833.0,2.090000,6.59,14569.38,3.950000

In [51]:
countries = pd.unique(data_in['Retailer country'])
years = pd.unique(data_in['Year'])

df = pd.DataFrame(index=countries, columns=years)

for year in years:
    df_any=[]
    for country in countries:
        df_any.append(data_in[(data_in['Retailer country']==country) &( data_in['Year']==year) ]['Gross profit'].sum())
       
    df[year]=df_any
pd.DataFrame.to_csv(df,'profit_country_year.csv')
df

                       2004         2005          2006         2007
United States   71020920.33  81388935.15  1.073967e+08  79728814.47
Canada          23848638.09  30460355.16  4.095771e+07  30476271.11
Japan           30462463.46  35019884.23  4.682255e+07  34825798.12
China           27395089.14  31917444.53  4.112311e+07  29391660.23
Singapore       16552042.46  19288774.96  2.530365e+07  19622174.51
Netherlands     14175503.98  17922500.80  2.439877e+07  19120427.87
Sweden           5883798.62   9633167.68  1.277359e+07  10998616.69
Finland         14400196.98  19247523.40  2.490754e+07  18517491.89
Denmark          5562686.25   6434056.48  8.241194e+06   4971472.86
France          27127518.98  29271502.24  3.458905e+07  26800488.20
United Kingdom  23264177.83  27986484.94  3.541902e+07  27004679.13
Austria         12351463.80  14141158.82  1.887558e+07  14193961.96
Mexico          11120421.23  17024802.79  2.432561e+07  15866498.26
Korea           16809027.34  20497260.33  2.513987e+07  19481796.27
Germany         24770281.76  26444369.48  3.254955e+07  23890284.58
Belgium          6618419.34  12317659.35  1.602303e+07  11700220.88
Italy           12968830.97  18786012.32  2.585363e+07  19459828.23
Spain           11431344.66  16028886.79  2.331056e+07  17389134.82
Brazil          11855083.35  13836254.38  1.807734e+07  13120852.27
Australia              0.00  10359493.62  1.980411e+07  14881848.54
Switzerland            0.00  10677164.20  1.736835e+07  13830501.10

#  Countries - product benefit

In [54]:
countries = pd.unique(data_in['Retailer country'])
products = pd.unique(data_in['Product line'])

df = pd.DataFrame(index=countries, columns=products)

for product in products:
    df_any=[]
    for country in countries:
        df_any.append(data_in[(data_in['Retailer country']==country) &( data_in['Product line']==product) ]['Gross profit'].sum())
        
    df[product]=df_any
pd.DataFrame.to_csv(df,'profit_country_productLine.csv')
df

,Camping Equipment,Personal Accessories,Outdoor Protection,Golf Equipment,Mountaineering Equipment
United States,96737911.69,1.510485e+08,7779275.78,57793398.03,26176293.64
Canada,38553643.97,5.069250e+07,3043347.90,22744644.81,10708839.21
Japan,42985701.04,6.340864e+07,3481385.45,25896647.20,11358331.19
China,40486800.09,5.049673e+07,3234605.01,24791506.78,10817659.10
Singapore,26822806.79,2.941333e+07,2023501.62,15487056.82,7019948.74
Netherlands,24147649.73,2.841614e+07,1791088.62,14697373.35,6564949.92
Sweden,8974665.88,1.794817e+07,593828.98,8357290.41,3415215.77
Finland,25904310.62,2.608576e+07,1996339.14,15907197.10,7179150.15
Denmark,7510045.25,1.377406e+07,671155.66,1987698.42,1266451.80
France,34192942.33,5.192042e+07,3042204.43,19692105.68,8940881.92
United Kingdom,34813697.47,4.591187e+07,3049844.66,20749872.89,9149070.95
Austria,14958612.15,2.970757e+07,1148983.69,9303546.15,4443455.13
Mexico,25582340.71,1.808008e+07,1840900.28,15208008.02,7626006.46
Korea,29479270.28,2.391117e+07,2465518.49,18101443.76,7970554.56
Germany,33075788.37,4.362392e+07,2899542.72,19252732.47,8802509.79
Belgium,13821485.06,1.945484e+07,986937.45,8105112.00,4290955.18
Italy,23711488.74,2.971381e+07,1750476.33,14916157.80,6976370.89
Spain,21619613.58,2.495916e+07,1618839.14,13440180.89,6522131.93
Brazil,16556747.94,2.481065e+07,1283196.80,9714196.13,4524746.18
Australia,15724178.44,1.365865e+07,708906.09,9408571.24,5545143.07
Switzerland,11139393.52,1.954707e+07,573404.54,6638902.22,3977243.21

# 2007 order type- country

In [58]:
countries = pd.unique(data_in['Retailer country'])
orders = pd.unique(data_in['Order method type'])

df = pd.DataFrame(index=countries, columns=orders)

for order in orders:
    df_quant=[]
    for country in countries:
#         df_benef.append(data_in[(data_in['Retailer country']==country) &( data_in['Order method type']==order) ]['Gross profit'].sum())
        df_quant.append(data_in[(data_in['Retailer country']==country) &( data_in['Order method type']==order) ]['Quantity'].sum())
       
    df[order]=df_quant
pd.DataFrame.to_csv(df,'order_country_year.csv')
df

,Telephone,Sales visit,Web,Special,Mail,E-mail,Fax
United States,2191376.0,1229878.0,11693389.0,55073.0,224692.0,67793.0,259876.0
Canada,247057.0,204138.0,3771627.0,106150.0,61902.0,1284249.0,47610.0
Japan,714597.0,178677.0,5032431.0,33631.0,125950.0,571171.0,130670.0
China,295186.0,187864.0,5526773.0,42206.0,6705.0,0.0,52211.0
Singapore,238306.0,346544.0,2837907.0,176676.0,13468.0,1159.0,174535.0
Netherlands,373563.0,143286.0,2629779.0,0.0,163467.0,74154.0,64511.0
Sweden,191443.0,53611.0,1239333.0,0.0,0.0,192692.0,4732.0
Finland,88426.0,201904.0,3246174.0,0.0,0.0,0.0,66988.0
Denmark,151300.0,101543.0,1043040.0,0.0,1580.0,143.0,3530.0
France,888744.0,675392.0,3731303.0,0.0,90510.0,5053.0,138611.0
United Kingdom,591503.0,202397.0,4492279.0,20776.0,5090.0,34763.0,31553.0
Austria,381941.0,273740.0,2058141.0,8920.0,0.0,0.0,20082.0
Mexico,84819.0,849148.0,2098995.0,106456.0,18663.0,0.0,17671.0
Korea,85393.0,638627.0,2984926.0,19334.0,44692.0,61984.0,67136.0
Germany,113991.0,454097.0,3449359.0,0.0,137541.0,880825.0,48798.0
Belgium,21710.0,206915.0,1828945.0,7907.0,0.0,0.0,59314.0
Italy,86594.0,326940.0,2632457.0,18376.0,0.0,419362.0,61966.0
Spain,119808.0,86888.0,2733485.0,1106.0,55950.0,37590.0,136888.0
Brazil,66863.0,1012.0,2444249.0,2031.0,0.0,2625.0,75209.0
Australia,317044.0,236946.0,1427536.0,8379.0,2845.0,8031.0,0.0
Switzerland,3180.0,213865.0,1556177.0,29781.0,0.0,1065.0,18123.0